export const GET_MOVIES = 'GET_MOVIES';
export const GET_WATCHLIST = 'GET_WATCHLIST';
export const ADD_TO_WATCHLIST = 'ADD_TO_WATCHLIST';
export const REMOVE_FROM_WATCHLIST = 'REMOVE_FROM_WATCHLIST';
